name: simple_remote_config
description: Simple Remote Config written in Dart
version: 1.0.0
repository: https://github.com/TheQuantumCrew/simple_remote_config

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
