name: simple_remote_config
description: A simple plugin for helping you to change your application's behaviors, settings,.. without updating the application via network JSON.
version: 1.1.0
topics: [remote, config]
issue_tracker: https://github.com/TheQuantumCrew/simple_remote_config/issues
repository: https://github.com/TheQuantumCrew/simple_remote_config

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
