name: Build, Test and Deploy to Pub.dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze

      - name: Test
        run: dart test --coverage=coverage

      - name: Versioning
        id: version
        run: "echo ::set-output name=version-number::$(grep 'version: ' pubspec.yaml | sed 's/version: //')"

      - name: Release to github
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.version.outputs.version-number }}
          generate_release_notes: true
