name: Build, Test and Deploy to Pub.dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze

      - name: Test
        run: dart test --coverage=coverage
